version: '3.3'
services:

  frontend:
    image: itdxl/foodgramfront:latest
    volumes:
      - ../frontend/:/app/result_build/
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  
  backend:
    image: itdxl/foodgramback:latest
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/app/static
      - media_volume:/app/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume:
  db_volume:
